### ISSUE TITLE
package-json-validator returns validation errors for valid field values

### ISSUE THREAD

**Issue by lkisac** [michaelfaith/package-json-validator#57] opened 2017-01-27 13:58 UTC
Validating [mysql](https://github.com/mysqljs/mysql) package.json through http://package-json-validator.com returns invalid for repository shortcut syntax and npm auto-populated fields.

Results:

{
  "valid": false,
  "errors": [
    "Url not valid for repository: mysqljs/mysql"
  ],
  "warnings": [
    "Missing recommended field: keywords",
    "Missing recommended field: bugs"
  ],
  "recommendations": [
    "Missing optional field: homepage"
  ]
}

Reference pull request [#1630](https://github.com/mysqljs/mysql/pull/1630)

**Comment by JoshuaKGoldberg** [comment] 2024-03-28 12:26
> "errors": ... "Url not valid for repository: mysqljs/mysql"

Alas, duplicate of #29.

> "warnings": ...
> "recommendations": ...

That's why they're not errors 🙂. They're not _required_, but are generally recommended to fill in.

Closing this as a duplicate, but someone please yell at me if I've misinterpreted. Cheers! 🧡

**Closed as not planned by JoshuaKGoldberg** 2024-03-28 12:26 UTC
